### ISSUE TITLE
ROOOOOOOOOCK

### ISSUE THREAD

**Issue by Darnelo-Inc** [Duzhinsky/chess#26]
Why are there rocks on the corners in this game?

![new](https://github.com/Duzhinsky/chess/assets/64681654/d128d604-54fa-476d-aeca-465528324beb)

**Comment by Duzhinsky** [comment]
cuz we're cool

**Comment by Darnelo-Inc** [comment]
When life puts rocks in your way, build something nice with them.
 
> Volksweisheit

**Comment by Duzhinsky** [comment]
Fixed
